- name: install and start nginx
  hosts: frontend
  become: yes # sudo kosam manam mobaxterm command lo -b istham indulo word  laga isthunam
  tasks:
  - name: install nginx
    ansible.builtin.package:
     name: nginx
     state: present

  - name: start nginx
    ansible.builtin.service:
     name: nginx
     state: started
     enabled: yes

